twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        'public': public
    globals:
        reCaptcha_key: '%env(RECAPTCHA_KEY)%'

when@test:
    twig:
        strict_variables: true
